data_configs:
  max_seq_length: 50
  max_span_length: 8
  width_embedding_dim: 100
model_configs:
  bert_dir: ./bert-base-uncased
  hidden_dropout_prob: 0.3
train_configs:
  max_epochs: 10
  batch_size: 32
  learning_rate: 0.00003
  task_learning_rate: 0.001
  warm_up_ratio: 0.2