data_configs:
  max_seq_length: 50
  max_span_length: 8
  width_embedding_dim: 150
model_configs:
  bert_dir: ./bert-base-uncased
  hidden_dropout_prob: 0.3
train_configs:
  max_epochs: 100
  batch_size: 32
  learning_rate: 0.000001
  task_learning_rate: 0.0005
  warm_up_ratio: 0.1
